add whether enabled & port number support for https
Telecominfraproject/ols-ucentral-schema pull request #17
Opened 2024-06-05 08:34 UTC by Cahb

2024-06-05 08:35 UTC, Cahb commented
Hey Jacky! Thanks for the changes, i've created a PR for a convinient discussion of these changes, if you don't mind;

We can discuss it here later on

2024-06-05 13:35 UTC, mikehansen1970 commented on ucentral.schema.json
> +                    "minimum": 443,
minimum for https should be 1
default for https should be 443

2024-06-05 13:37 UTC, mikehansen1970 requested changes
Please fix minimum and default for the ucentral.schema.json so that aligns with the pretty and full versions.
These schema files can, and should be generated using the generate.sh script in the repo which will ensure consistency.

2024-06-06 03:13 UTC, jacky1100002 commented
Thanks Mike. I will modify it according to your suggestion.

2024-08-06 09:49 UTC, merged